# Generated by Django 4.1.3 on 2022-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
                ('cultivo', models.CharField(max_length=50)),
                ('volumen', models.IntegerField()),
                ('cosecha', models.CharField(max_length=50)),
                ('tipo_de_precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=50)),
                ('gremio', models.CharField(max_length=50)),
                ('cosecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
                ('gremio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
                ('cultivo', models.CharField(max_length=50)),
                ('volumen', models.IntegerField()),
                ('cosecha', models.CharField(max_length=50)),
                ('tipo_de_precio', models.CharField(max_length=50)),
            ],
        ),
    ]
